name: build and push

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get yt-dl version
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: "curl -s https://pypi.org/pypi/youtube_dl/json | jq -r .info.version"
      - name: Get yt-dlp version
        uses: sergeysova/jq-action@v2
        id: versionp
        with:
          cmd: "curl -s https://pypi.org/pypi/yt_dlp/json | jq -r .info.version"
      - name: Check for existing image yt-dl
        id: existing-image-ytdl
        uses: javajawa/check-registry-for-image@v1
        with:
          registry: docker.io
          repository: infanf/youtube-dl
          tag: ytdl-${{ steps.version.outputs.value }}
      - name: Check for existing image yt-dlp
        id: existing-image-ytdlp
        uses: javajawa/check-registry-for-image@v1
        with:
          registry: docker.io
          repository: infanf/youtube-dl
          tag: ytdlp-${{ steps.versionp.outputs.value }}
      - name: Build and push
        id: docker_build
        if: ${{ steps.existing-image-ytdl.outputs.exists == 'false' && steps.existing-image-ytdlp.outputs.exists == 'false'}}
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          tags: |
            infanf/youtube-dl:latest
            infanf/youtube-dl:ytdl-${{ steps.version.outputs.value }}
            infanf/youtube-dl:ytdlp-${{ steps.versionp.outputs.value }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
