name: Build ffmpeg

on: [workflow_call]
jobs:
  ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Check for existing image
        id: existing-image
        uses: hipcamp/docker-tag-exists@v1
        with:
          image: infanf/ffmpeg
          tag: '5.1.1'
      - name: Build and push
        id: docker_build
        if: ${{ steps.existing-image.outputs.tag-exists == 'false'}}
        uses: docker/build-push-action@v2
        with:
          file: ffmpeg.Dockerfile
          platforms: linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7
          push: true
          tags: |
            infanf/ffmpeg:latest
            infanf/ffmpeg:5.1.1
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
