name: Build youtube-dl

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"

jobs:
  ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check for existing image
        id: existing-image
        uses: hipcamp/docker-tag-exists@v1
        with:
          image: infanf/ffmpeg
          tag: '6.1'
      - name: Set up QEMU
        if: ${{ steps.existing-image.outputs.tag-exists == 'false'}}
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        if: ${{ steps.existing-image.outputs.tag-exists == 'false'}}
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        if: ${{ steps.existing-image.outputs.tag-exists == 'false'}}
        uses: docker/build-push-action@v2
        with:
          file: ffmpeg.Dockerfile
          platforms: linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7
          push: true
          tags: |
            infanf/ffmpeg:latest
            infanf/ffmpeg:6.1
      - name: Image digest
        if: ${{ steps.existing-image.outputs.tag-exists == 'false'}}
        run: echo ${{ steps.docker_build.outputs.digest }}

  build:
    needs: [ffmpeg]
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get yt-dlp version
        uses: sergeysova/jq-action@v2
        id: versionp
        with:
          cmd: "curl -s https://pypi.org/pypi/yt_dlp/json | jq -r .info.version"
      - name: Check for existing image yt-dlp
        id: existing-image-ytdlp
        uses: hipcamp/docker-tag-exists@v1
        with:
          image: infanf/youtube-dl
          tag: ytdlp-${{ steps.versionp.outputs.value }}
      - name: Set up QEMU
        if: ${{ steps.existing-image-ytdlp.outputs.tag-exists == 'false'}}
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        if: ${{ steps.existing-image-ytdlp.outputs.tag-exists == 'false'}}
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        if: ${{ steps.existing-image-ytdlp.outputs.tag-exists == 'false'}}
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7
          push: true
          tags: |
            infanf/youtube-dl:latest
            infanf/youtube-dl:ytdlp-${{ steps.versionp.outputs.value }}
      - name: Image digest
        if: ${{ steps.existing-image-ytdlp.outputs.tag-exists == 'false'}}
        run: echo ${{ steps.docker_build.outputs.digest }}
